Repository horrokotoj/Gengar, pull requests merged in 2021-04, with the labels that each got.

#21 Front end navigation bar person screens
  README.md
  VaccMe/App.js
  VaccMe/app/assets/1177.png
  VaccMe/app/assets/Biggest ASSet.jpg
  VaccMe/app/context/AuthContext.js
  VaccMe/app/navigators/AuthNavigator.js
  VaccMe/app/navigators/Navigator.js
  VaccMe/app/navigators/PersonNavigator.js
  VaccMe/app/screens/BusinessLoginScreen.js
  VaccMe/app/screens/BusinessScreen.js
  VaccMe/app/screens/PersonBookScreen.js
  VaccMe/app/screens/PersonCalendarScreen.js
  VaccMe/app/screens/PersonCertScreen.js
  VaccMe/app/screens/PersonLoginScreen.js
  VaccMe/app/screens/PersonQrScreen.js
  VaccMe/app/screens/PersonScreen.js
  VaccMe/app/screens/PersonSettingsScreen.js
  VaccMe/app/screens/Splash.js
  VaccMe/app/screens/WelcomeScreen.js
  VaccMe/app/styleSheets/StyleSheets.js
  VaccMe/package-lock.json
  VaccMe/package.json
  media/BusinessLoginScreen.png
  media/PersonBookScreen.png
  media/PersonCalendarScreen.png
  media/PersonCertScreen.png
  media/PersonLoginScreen.png
  media/PersonQrScreen.png
  media/PersonSettingsScreen.png
  media/Splash.png
  media/WelcomeScreen.png
Labels: enhancement

#28 Working QR scanner on business page + documentation
  README.md
  VaccMe/app.json
  VaccMe/app/navigators/BusinessNavigator.js
  VaccMe/app/navigators/Navigator.js
  VaccMe/app/screens/BusinessHomeScreen.js
  VaccMe/app/screens/BusinessLoginScreen.js
  VaccMe/app/screens/BusinessQrScreen.js
  VaccMe/app/screens/BusinessScreen.js
  VaccMe/app/styleSheets/StyleSheets.js
  VaccMe/babel.config.js
  VaccMe/package-lock.json
  VaccMe/package.json
  media/BusinessHomeScreen.png
  media/BusinessQrScreen.png
Labels: documentation, enhancement

#38 Added usertokens to secure store. This makes it possible to stay sign…
  README.md
  VaccMe/app/navigators/Navigator.js
  VaccMe/app/screens/PersonCalendarScreen.js
  VaccMe/package-lock.json
  VaccMe/package.json
Labels: enhancement

#40 Network cert
  VaccMe/app/navigators/Navigator.js
  VaccMe/app/screens/PersonBookScreen.js
  VaccMe/app/screens/PersonCalendarScreen.js
  VaccMe/app/screens/PersonCertScreen.js
  VaccMe/app/screens/PersonQrScreen.js
  VaccMe/app/styleSheets/StyleSheets.js
  media/PersonBookScreen.png
  media/PersonCalendarScreen.png
  media/PersonCertScreen.png
  media/PersonQrScreen.png
Labels: High prio
